language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

sudo: false

matrix:
  fast_finish: true

install:
  - composer install --no-interaction --prefer-source

script:
  - ./vendor/bin/phing build

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
